"""autogen-check-runtime-and-db-hardening

Revision ID: 3293fd0bfee2
Revises: 0009
Create Date: 2026-02-21 23:51:16.761351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3293fd0bfee2"
down_revision: Union[str, None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inbox_items_created_at"), table_name="inbox_items")
    op.drop_index(op.f("ix_inbox_items_surfaced"), table_name="inbox_items")
    op.drop_index(op.f("ix_sessions_created_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_updated_at"), table_name="sessions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_sessions_updated_at"), "sessions", ["updated_at"], unique=False)
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_created_at"), "sessions", ["created_at"], unique=False)
    op.create_index(op.f("ix_inbox_items_surfaced"), "inbox_items", ["surfaced"], unique=False)
    op.create_index(op.f("ix_inbox_items_created_at"), "inbox_items", ["created_at"], unique=False)
    # ### end Alembic commands ###
